# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loomcycle < Formula
  desc "Agentic runtime — one Go binary owning the LLM tool-use loop"
  homepage "https://github.com/denn-gubsky/loomcycle"
  version "1.17.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.17.1/loomcycle-darwin-amd64.tar.gz"
      sha256 "4c01acabab6c4626dd38fcb17af16d5ad688857fa10de8fc9fe3b2baacbaf3b6"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.17.1/loomcycle-darwin-arm64.tar.gz"
      sha256 "6d4ca472c3ee437f520d53ebc0dfc31c918b8fad5604a66038c2ec6b816c86f7"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.17.1/loomcycle-linux-amd64.tar.gz"
      sha256 "ee081f2c3cdcf37684fc4583614f3b5deda0ce57b6001a292b8a01d99f72e741"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.17.1/loomcycle-linux-arm64.tar.gz"
      sha256 "b6a1d50afa937806282eb15347dd9ee99bf6b848a8dc5656eb9348cc870384c6"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (v0.11.1+):

        loomcycle init       # bootstrap ~/.config/loomcycle/loomcycle.yaml
        # set $LOOMCYCLE_AUTH_TOKEN and at least one provider key
        # (ANTHROPIC_API_KEY / OPENAI_API_KEY / DEEPSEEK_API_KEY)
        loomcycle doctor     # verify your setup
        loomcycle            # start the server on 127.0.0.1:8787

      For background-service operation on macOS, see Homebrew's
      `brew services`. For Docker-based deployment, pull from
      docker.io/denngubsky/loomcycle (v0.11.2+).
    EOS
  end

  test do
    assert_match "version=", shell_output("#{bin}/loomcycle --version")
  end
end
