# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loomcycle < Formula
  desc "Agentic runtime — one Go binary owning the LLM tool-use loop"
  homepage "https://github.com/denn-gubsky/loomcycle"
  version "1.6.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.6.7/loomcycle-darwin-amd64.tar.gz"
      sha256 "9bd6e2bfba7332b2164f8dccf3d7770e4f5b596159744fb4f861593c960bdfcb"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.6.7/loomcycle-darwin-arm64.tar.gz"
      sha256 "c865decf48a8582af258ef6449bb279e10d3c8ef9fa1a1be10cdb9bc90d3ab96"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.6.7/loomcycle-linux-amd64.tar.gz"
      sha256 "f45c52df24f3f7c0775d9a900e1a70a5f5b429011f370340d00d2549979d55b4"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v1.6.7/loomcycle-linux-arm64.tar.gz"
      sha256 "da93b3846fc4285366c80b9ca57ae45d521d79d210424a9d7937100ef64a6f01"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (v0.11.1+):

        loomcycle init       # bootstrap ~/.config/loomcycle/loomcycle.yaml
        # set $LOOMCYCLE_AUTH_TOKEN and at least one provider key
        # (ANTHROPIC_API_KEY / OPENAI_API_KEY / DEEPSEEK_API_KEY)
        loomcycle doctor     # verify your setup
        loomcycle            # start the server on 127.0.0.1:8787

      For background-service operation on macOS, see Homebrew's
      `brew services`. For Docker-based deployment, pull from
      docker.io/denngubsky/loomcycle (v0.11.2+).
    EOS
  end

  test do
    assert_match "version=", shell_output("#{bin}/loomcycle --version")
  end
end
