# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loomcycle < Formula
  desc "Agentic runtime — one Go binary owning the LLM tool-use loop"
  homepage "https://github.com/denn-gubsky/loomcycle"
  version "0.23.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v0.23.4/loomcycle-darwin-amd64.tar.gz"
      sha256 "e0919d78a6acd5a23b9c14158635a126b63873476b0df91875027229d0bed6d8"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v0.23.4/loomcycle-darwin-arm64.tar.gz"
      sha256 "acb8a0d4127c2773aaee13776db80cd47a4c6ff738fecdee97d04331fe869cc2"

      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v0.23.4/loomcycle-linux-amd64.tar.gz"
      sha256 "69a82500cb70c86dceb9b7aa543eef93ba4bd05ccfdda9be1648bb79bd3b2a02"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/denn-gubsky/loomcycle/releases/download/v0.23.4/loomcycle-linux-arm64.tar.gz"
      sha256 "e72df83a003230fc7461293619d4170d71e74d2a2ce056ad3b963803828b5bcd"
      define_method(:install) do
        bin.install "loomcycle"
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (v0.11.1+):

        loomcycle init       # bootstrap ~/.config/loomcycle/loomcycle.yaml
        # set $LOOMCYCLE_AUTH_TOKEN and at least one provider key
        # (ANTHROPIC_API_KEY / OPENAI_API_KEY / DEEPSEEK_API_KEY)
        loomcycle doctor     # verify your setup
        loomcycle            # start the server on 127.0.0.1:8787

      For background-service operation on macOS, see Homebrew's
      `brew services`. For Docker-based deployment, pull from
      docker.io/denngubsky/loomcycle (v0.11.2+).
    EOS
  end

  test do
    assert_match "version=", shell_output("#{bin}/loomcycle --version")
  end
end
